# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x05order\x1a\x1bgoogle/protobuf/empty.proto\"\x15\n\x07OrderId\x12\n\n\x02id\x18\x01 \x01(\t\"$\n\x12OrderCreateRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x01\"J\n\rOrderResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1d\n\x06status\x18\x02 \x01(\x0e\x32\r.order.Status\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01*S\n\x06Status\x12\x0b\n\x07\x43REATED\x10\x00\x12\x14\n\x10\x41WAITING_PAYMENT\x10\x01\x12\x08\n\x04PAID\x10\x02\x12\r\n\tCOMPLETED\x10\x03\x12\r\n\tCANCELLED\x10\x04\x32\xb7\x01\n\x0cOrderService\x12>\n\x0b\x43reateOrder\x12\x19.order.OrderCreateRequest\x1a\x14.order.OrderResponse\x12\x30\n\x08GetOrder\x12\x0e.order.OrderId\x1a\x14.order.OrderResponse\x12\x35\n\x0b\x43\x61ncelOrder\x12\x0e.order.OrderId\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=188
  _globals['_STATUS']._serialized_end=271
  _globals['_ORDERID']._serialized_start=51
  _globals['_ORDERID']._serialized_end=72
  _globals['_ORDERCREATEREQUEST']._serialized_start=74
  _globals['_ORDERCREATEREQUEST']._serialized_end=110
  _globals['_ORDERRESPONSE']._serialized_start=112
  _globals['_ORDERRESPONSE']._serialized_end=186
  _globals['_ORDERSERVICE']._serialized_start=274
  _globals['_ORDERSERVICE']._serialized_end=457
# @@protoc_insertion_point(module_scope)
